[env]

[cursor.style]
shape = "Underline"
blinking = "Always"

# to set your default shell
# [shell]
# program = "/usr/bin/zsh"
# args = ["-l"]

[font]
size = 14.0

[font.normal]
family = "Agave Nerd Font"

[font.bold]
family = "Agave Nerd Font"

[font.italic]
family = "Agave Nerd Font"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 1
blur = true
title = "Hoppix"
decorations_theme_variant = "Dark"

[window.padding]
x = 5
y = 5

[window.dimensions]
columns = 90
lines = 25

[scrolling]
history = 50000
multiplier = 4

[colors.normal]
black = "#121319"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"
 
[colors.primary]
background = "#1f2335"

