require("hoppix.remap")
require("hoppix.lazy")
require("hoppix.plugins")
require("hoppix.editor")
require("hoppix.colorscheme")
require("hoppix.telescope")
require("hoppix.treesitter")
require("hoppix.harpoon")
require("hoppix.fugitive")

